name: my_utils
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.1
  country_flags: ^2.2.0
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/icons/
    - assets/lang/
    - assets/lottie/
