name: my_utils
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: '>=3.4.0-282.3.beta<4.0.0'
  flutter: ">=3.2.0"

dependencies:
  cached_network_image: ^3.3.1
  cached_network_image_platform_interface: ^4.1.1
  country_flags: ^3.0.0
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  shimmer: ^3.0.0
  vector_graphics: ^1.1.18


flutter:
  assets:
    - lib/assets/